package net.binder.api.notification.entity;

public enum NotificationType {
    BIN_REGISTRATION_APPROVED,
    BIN_REGISTRATION_REJECTED,

    BIN_MODIFICATION_APPROVED,
    BIN_MODIFICATION_REJECTED,

    BIN_COMPLAINT_APPROVED,
    BIN_COMPLAINT_REJECTED,

    BIN_LIKED,

    BIN_MODIFIED,
    BIN_DELETED
}
