package net.binder.api.notification.entity;

public enum NotificationType {
    BIN_REGISTRATION_APPROVED,
    BIN_REGISTRATION_REJECTED,

    BIN_MODIFICATION_APPROVED,
    BIN_MODIFICATION_REJECTED,

    BIN_REPORT_MODIFIED,
    BIN_REPORT_DELETED,
    BIN_REPORT_REJECTED,

    BIN_LIKED,
    BIN_DISLIKED,
}
